// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6oWPXv08xJn1KMfzXUmeXaU2Q2Lb0f70',
    appId: '1:20285650692:web:8867cf51b0cf0210ed8251',
    messagingSenderId: '20285650692',
    projectId: 'consultationapp-93047',
    authDomain: 'consultationapp-93047.firebaseapp.com',
    storageBucket: 'consultationapp-93047.firebasestorage.app',
    measurementId: 'G-WGHBBMFRN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtvZjyKJrlpZSobLVSTSFKrAM6FuZvmO4',
    appId: '1:20285650692:android:f2ba561952204ecfed8251',
    messagingSenderId: '20285650692',
    projectId: 'consultationapp-93047',
    storageBucket: 'consultationapp-93047.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqc75g99Lo7sJlDGMBa597z_rD9nO5BNo',
    appId: '1:20285650692:ios:4f55095e9b1ec121ed8251',
    messagingSenderId: '20285650692',
    projectId: 'consultationapp-93047',
    storageBucket: 'consultationapp-93047.firebasestorage.app',
    iosBundleId: 'com.example.patientPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqc75g99Lo7sJlDGMBa597z_rD9nO5BNo',
    appId: '1:20285650692:ios:4f55095e9b1ec121ed8251',
    messagingSenderId: '20285650692',
    projectId: 'consultationapp-93047',
    storageBucket: 'consultationapp-93047.firebasestorage.app',
    iosBundleId: 'com.example.patientPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6oWPXv08xJn1KMfzXUmeXaU2Q2Lb0f70',
    appId: '1:20285650692:web:ae364ed2c11579e1ed8251',
    messagingSenderId: '20285650692',
    projectId: 'consultationapp-93047',
    authDomain: 'consultationapp-93047.firebaseapp.com',
    storageBucket: 'consultationapp-93047.firebasestorage.app',
    measurementId: 'G-4CNTMKGVK7',
  );
}
